version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: khj
      POSTGRES_PASSWORD: khj
      POSTGRES_DB: toy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/toy

volumes:
  postgres_data: